### ISSUE TITLE
Error: Cannot find module './bin-linux/segfault'

### ISSUE THREAD

**Issue by trusktr** [node-3d/webgl-raub#10]
Hello again. I must say, this package is pretty neat! I've gotten [lume/glas](https://github.com/lume/glas) (port of Three.js to [AssemblyScript](http://assemblyscript.org/)) to run inside unit tests ran with [as-pect](https://github.com/jtenner/as-pect/issues) (a test runner for AssemblyScript). I polyfilled WebGL on the Node.js side with webgl-raub, then used [ASWebGLue](https://github.com/battlelinegames/ASWebGLue) (WebGL bindings for AssemblyScript) to set up the JS WebGL glue code and for the `WebGL` API inside AssemblyScript code, and it works great in Linux (headlessly with `xvfb-maybe` for unit testing, but it will work great with a window for actual applications). Really awesome that webgl-raub exists to allow such things.

I'm trying to get this setup working in Windows now. First I'm trying in WSL Bash, and when I try to run unit tests I run into this error:

```
Error: Cannot find module './bin-linux/segfault'
Require stack:
- /mnt/d/src/lume+lume/packages/glas/node_modules/segfault-raub/index.js
- /mnt/d/src/lume+lume/packages/glas/node_modules/webgl-raub/core.js
- /mnt/d/src/lume+lume/packages/glas/node_modules/webgl-raub/js/webgl.js
- /mnt/d/src/lume+lume/packages/glas/node_modules/webgl-raub/index.js
```

When I check to see what is in the `segfault-raub` package, I see there is not `bin-linux/` folder:

```
$ ls -l node_modules/segfault-raub/
total 12
-rwxrwxrwx 1 trusktr trusktr  260 Oct 26  1985 index.js
-rwxrwxrwx 1 trusktr trusktr  232 Oct 26  1985 install.js
-rwxrwxrwx 1 trusktr trusktr 1538 Oct 26  1985 LICENSE
-rwxrwxrwx 1 trusktr trusktr 1860 Mar 12 21:27 package.json
-rwxrwxrwx 1 trusktr trusktr 1857 Oct 26  1985 README.md
```

Any idea what is happening?

**Comment by raub** [comment]
Hello! The folders "bin-*" appear during the `postinstall` step. The `postinstall` step simply downloads the binaries from the repository Releases section. You can find the related binaries manually for that matter. So, why is it missing, I would guess, either `postinstall` is not called during the instalation, or it is broken for WSL somehow.

In `package.json` you can see this section:

```
	"scripts": {
		"postinstall": "node install"
	},
```

And I wonder what is the related console output in your case. Usually, when NPM finishes its business, the command `node install` start immediately, and it is visible in console. You can also try to start it manually by running `npm run postinstall`.

Have you made any progress on this issue since the initial post?

**Comment by trusktr** [comment]
Thanks for the info! I will circle back to this soon.

**Comment by trusktr** [comment]
I am having the issue still. For example, here's CI failing due to the error:

https://github.com/lume/lume/runs/2550548483?check_suite_focus=true

Investigating...

**Comment by trusktr** [comment]
I think it may be because I'm running `lerna` with the `--ignore-scripts` option, so maybe `postinstall` is not firing.

Is there an official standard way to have OS-specific binaries installed, without using a package.json script?

**Comment by trusktr** [comment]
Yep, that was it!!

As a temporary solution, I made sure that one of my packages is bootstrapped separately without `--ignore-scripts`.

At the moment, the package in question does not need to be linked to other packages, so this works out fine.

But in the future other packages will depend on this package, but I need lerna to bootstrap without running their scripts, then I run scripts later.

However, segfault-raub is a dependency of my packages, so it is not managed by lerna, so I don't know how to have lerna trigger `postinstall` only for segfault-raub.

If there is no official way to install binaries without package.json scripts, I'll just add my own build step that calls `node node_modules/segfault-raub/install.js`.

**Comment by raub** [comment]
There is only one way I know of, to install the binary dependencies without using scripts. And that is to actually publish them to NPM as-is, for all platforms at once. 

If you look closely, you may notice, my packages have their binary dependencies always installed to platform-specific directory. This is actually a rudiment from the time when I published all the binaries to NPM.

See this for example: https://github.com/node-3d/deps-opengl-raub/tree/2.0.0

The downside, and why I am now using scripts, is the size of, well, everything:

- Install a module - download 3x more data.
- Publish a module - upload 3x more data (and may be you have the same binaries untouched!).
- Pack a single-executable app - pack 3x more data (or bother to remove whatever is not needed).

So, I even resorted to `postinstall` that would delete the excess files after `npm i`... And then, in the end, I switched to downloading in `postinstall`.
