### ISSUE TITLE
Error: dlopen(bin-osx/webgl.node).  Library not loaded: @rpath/glew.dylib

### ISSUE THREAD

**Issue by wufangcan** [node-3d/webgl-raub#11]

**Comment by wufangcan** [comment]
Hello, 
I ran this demo on macOS, but the following error occurred, how can I solve it?

Error: dlopen(/webgl-raub/bin-osx/webgl.node, 1): Library not loaded: @rpath/glew.dylib
  Referenced from: /Users/Carl/WorkSpace/GitHub/electron/webgl-raub/bin-osx/webgl.node
  Reason: image not found

**Comment by raub** [comment]
Hello. Please check if that file exists under `/Users/Carl/WorkSpace/GitHub/electron/webgl-raub/node_modules/deps-opengl-raub/bin-osx/glew.dylib`, or anywhere under the project directory at all.

If it is not there, the library might have failed to install properly. And if it is there, it might be a result of some system-specific changes in OSX. I can't actually test this as I don't have an OSX device. And also I can't validate it with CI as it doesn't have a visual interface available for GL to run on.

Although, the module is known to have worked under OSX. I wonder if you could try it on any other OSX machine as well. I will also ask my friend who has one to try running this.

P.S.: Does it have anything to do with `electron` in your directory path anyway?
