### ISSUE TITLE
Headless rendering

### ISSUE THREAD

**Issue by extremeheat** [node-3d/webgl-raub#14]
Hi, this is really cool. Is there any way to render headless, without the use of a GUI? It would be nice to be able to get a frame buffers stream in JS.

**Comment by raub** [comment]
Hi. It should be possible to use an invisible window. For example with GLFW, as described here: https://www.glfw.org/docs/latest/context.html#context_offscreen

OpenGL needs at least some window, and the invisible one is fine too. Depending on your setup there are different approaches, the simplest being to use `glfw-raub` as in examples https://github.com/node-3d/webgl-raub/blob/master/examples/package.json

You have to set the window visibility hint before creating the window. It should work the same way if you want to use the `3d-core-raub` module - you'll have to set the hint before calling the `init`.
