### ISSUE TITLE
Incorrect typescript definitions

### ISSUE THREAD

**Issue by aximili-dev** [node-3d/webgl-raub#15]
The `index.d.ts` file has some semicolons which cause the following error to be throw when trying to compile a typescript project that uses this library:

```
node_modules/webgl-raub/index.d.ts:24:4 - error TS1036: Statements are not allowed in ambient contexts.
```

I've forked the repo and created a fix to be able to use it in my own projects, I've also submitted a pull request with the fix

**Comment by raub** [comment]
Hello. Thank you, I've published the proposed changes as webgl-raub@2.2.5
