### ISSUE TITLE
Comparison with headless-gl

### ISSUE THREAD

**Issue by stepancar** [node-3d/webgl-raub#24]
Hello! Thank you for this project!
We are using https://github.com/stackgl/headless-gl to render images on node js with pixijs.
It does not support webgl2, so we are trying to find a replacement. 
Does your project allow to use webgl2?
Does it provide similar performance to https://github.com/stackgl/headless-gl ?

In order to utilize nvidia gpu we build headless-gl passing 
```
'libraries': [
              '-lEGL',
              '-lGLESv2'
 ],
```
to linker and it utilizes egl provided by nvidia drivers.
https://github.com/stackgl/headless-gl/compare/master...Lumen5:headless-gl:master

Is it possible to do the same with your library?

Thank you!

**Comment by raub** [comment]
Hello. The WebGL bindings provided by this module only **mimic** WebGL and WebGL2 interfaces. Just enough to run THREE.js demos. E.g., the `WebGLContext` is fake, and there is no actual canvas to create it on. The bindings may also export some extra features or miss certain parts of WebGL API that were not essential to run THREE.js demos.


> Does it provide similar performance to https://github.com/stackgl/headless-gl ?

Sorry, I have no idea regarding the performance of `headless-gl`. In terms of performance, `webgl-raub` calls the GL methods as directly as possible, see [example](https://github.com/node-3d/webgl-raub/blob/master/src/cpp/buffers.cpp). It's just a way to make those C++ calls from JS. This specific module does not handle nor constrain the GL context (and window). So, it may be used in headless mode if necessary.


> Does your project allow to use webgl2?

To some extent. It may depend on how third-party code determines the WebGL version and how it uses it. For instance, THREE.js thinks this is WebGL2. You might try using it with PIXI and find out if something specific is missing. Also, this project certainly allows something like `gl.missingFeature = fix;` or even forking it completely.


> Is it possible to do the same with your library?

It should be possible to rebuild the bindings with any library you want, as long as the linker is satisfied. The currently used libraries are explicitly listed in GYP [here](https://github.com/node-3d/webgl-raub/blob/master/src/binding.gyp). If you fork and replace them, and the dependencies are satisfied, then why not.


Improving compatibility with PIXI may also be useful for this project. Have you had any luck since time of the original post?

**Comment by raub** [comment]
After further reviewing the sources of `headless-gl`, I'm pretty confident that `webgl-raub` has a more simple and performant approach. BUT! Note that you've aimed to use some specific kind of EGL lib, and that might make sense in case of `headless-gl` - as it uses EGL to create its own context. Which as I have also stated above `webgl-raub` does not do, and neither it depends on EGL for that matter.

Instead, `webgl-raub` "thinks" that the context is already there, it is your problem how you create it (e.g. using `glfw-raub`). This is why `webgl-raub` simply relays your calls to C++ land - it simply assumes that the right context is always in place.


> In order to utilize nvidia gpu we build headless-gl passing

I'm not sure I understand the limitations of `headless-gl` in relation to NVidia GPUs, but there is no such concern for `webgl-raub`. I can showcase my point with this [Steam game](https://store.steampowered.com/app/1196080/Space_Simulation_Toolkit/). It uses an old version of this very module to render the stuff - the whole point of this game is direct manipulation of many GPU resources. And it even primarily targeted NVidia GPUs before OpenCL support was added.


So, I guess you might use this project as-is for your purpose - no need to recompile. The main issue is compatibility with PIXI and its specific WebGL2 requirements.

**Comment by raub** [comment]
Hey @stepancar, I've just found this snippet:

```
{
  "name": "pixi-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "3d-core-raub": "^3.6.0",
    "pixi.js": "^6.0.4"
  }
}
```

```
const init = require('3d-core-raub');
global.self = global;

const { loop, canvas, Image, webgl, doc } = init();

global.self.WebGLRenderingContext = webgl.WebGLRenderingContext;
global.self.addEventListener = doc.addEventListener.bind(doc);
global.self.removeEventListener = doc.removeEventListener.bind(doc);
webgl.getContextAttributes = () => ({ stencil: true });
webgl.isContextLost = () => false;
webgl.getInternalformatParameter = () => 1;

Image.prototype.fillRect = () => {};

const createOld = doc.createElement.bind(doc);
doc.createElement = (name) => {
    if (name === 'div' || name === 'a') {
        return { style: {} };
    }
    return createOld(name);
};

Object.defineProperty(Image.prototype, 'onerror', {
    get() { return this.listeners('error'); },
    set(cb) { cb ? this.on('error', cb) : this.removeAllListeners('error'); },
});
Object.defineProperty(Image.prototype, 'onload', {
    get() { return this.listeners('load'); },
    set(cb) { cb ? this.on('load', cb) : this.removeAllListeners('load'); },
});

const enforceF32 = v => v instanceof Array ? new Float32Array(v) : v;
const _bufferSubData = webgl.bufferSubData;
webgl.bufferSubData = (target, offset, v) => {
	if (v instanceof ArrayBuffer) {
		v = new Float32Array(v);
	}
	return _bufferSubData(target, offset, enforceF32(v));
};


// based on https://pixijs.io/examples/#/demos-basic/container.js

const PIXI = require('pixi.js');
const app = new PIXI.Application({
    width: 800,
    height: 600,
    backgroundColor: 0x1099bb,
    resolution: window.devicePixelRatio || 1,
    view: canvas,
});

const container = new PIXI.Container();

app.stage.addChild(container);

// Create a new texture
const texture = PIXI.Texture.from('https://pixijs.io/examples/examples/assets/bunny.png');

// Create a 5x5 grid of bunnies
for (let i = 0; i < 25; i++) {
    const bunny = new PIXI.Sprite(texture);
    bunny.anchor.set(0.5);
    bunny.x = (i % 5) * 40;
    bunny.y = Math.floor(i / 5) * 40;
    container.addChild(bunny);
}

// Move container to the center
container.x = app.screen.width / 2;
container.y = app.screen.height / 2;

// Center bunny sprite in local container coordinates
container.pivot.x = container.width / 2;
container.pivot.y = container.height / 2;

// Listen for animate update
app.ticker.add((delta) => {
    // rotate the container!
    // use delta to create frame-independent transform
    container.rotation -= 0.01 * delta;
});
```

It worked for the versions specified and for this PIXI example. That might be a good starting point.

**Comment by raub** [comment]
https://github.com/node-3d/3d-core-raub/blob/master/examples/pixi/index.js

Added this example and made sure it works with all the up-to-date packages.

**Comment by stepancar** [comment]
@raub , thank you! I tried, but got this error

```
 ^

Error: Cannot find module './bin-darwin-arm64/segfault'
Require stack:
- /Users/stepancar/Desktop/projects/3d-core-raub/examples/pixi/node_modules/segfault-raub/index.js
- /Users/stepancar/Desktop/projects/3d-core-raub/examples/pixi/node_modules/webgl-raub/core.js
- /Users/stepancar/Desktop/projects/3d-core-raub/examples/pixi/node_modules/webgl-raub/js/webgl.js
- /Users/stepancar/Desktop/projects/3d-core-raub/examples/pixi/node_modules/webgl-raub/index.js
- /Users/stepancar/Desktop/projects/3d-core-raub/examples/pixi/node_modules/3d-core-raub/js/index.js
- /Users/stepancar/Desktop/projects/3d-core-raub/examples/pixi/node_modules/3d-core-raub/index.js
- /Users/stepancar/Desktop/projects/3d-core-raub/examples/pixi/index.js
```

I'm running it on macos, m1 cpu

**Comment by stepancar** [comment]
But I think it's related to this issue https://github.com/node-3d/webgl-raub/issues/23

**Comment by raub** [comment]
Yes, there are no precompiled M1 binaries. I build the binaries with GitHub Actions and there is no M1 runner. Maybe it is possible to cross-compile an M1 binary from MacOS x64, but I have no idea how to.

By the way... why don't you just use headless chromium (e.g. puppeteer) to render what you need and make screenshots? It's quite capable, and I believe there shouldn't be a problem with NVidia GPU beside it using ANGLE. So, if you don't use GL-CUDA interop, the existing browser environments may be a better choice.

**Comment by stepancar** [comment]
@raub , we used headless chrome for rendering before, but switched to nodejs with headless gl, because it's context starts much faster

**Comment by stepancar** [comment]
@raub thank you for your explanation, I will try to integrate your library
