### ISSUE TITLE
Is all extension unavailable?

### ISSUE THREAD

**Issue by axmand** [node-3d/webgl-raub#5]
When I used webgl1 extension, there was an undefined method error and no method bindings in the source code. Is webgl extension not available?
```javascript
  const ext = gl.getExtension("OES_vertex_array_object"),
    vao = ext.createVertexArrayOES();
  ext.bindVertexArrayOES(vao);
```

**Comment by raub** [comment]
Hello! You are right, there is currently no direct support for extensions.

Do you only need this one, or all of them? This one seems not so hard to start with, actually.

**Comment by axmand** [comment]
Yes, I see the implementation of the extension [Code](https://github.com/KhronosGroup/WebGL/blob/master/sdk/demos/google/resources/OESVertexArrayObject.js) , but I will definitely need more plugin support in the future. The workload looks huge to support those all plugins 😭 .

**Comment by raub** [comment]
Hey, @axmand can you try the [v1.2.0](https://github.com/node-3d/webgl-raub/releases/tag/v1.2.0) release for your VAO needs?

**Comment by axmand** [comment]
Thanks very much, @raub , it works well with '3d-core-raub' by replace the 'webgl-raub' in node_modules. 
![image](https://user-images.githubusercontent.com/5127112/51786424-ff1ab300-219e-11e9-8bdf-87aab4b078bc.png)


While I found some differences:
1. gl.bufferData(target, srcData, usage) in chrome can use ArrayBuffer directly, but webgl-raub prompts error "Argument 1 must be an array buffer', explain as follows.
``` javascript
const buffer = new Float32Array([]);
//works well in webgl-raub 
gl.bufferData(target, buffer , usage) 

//buffer from fetch
const buffer2 = response.arrayBuffer();
//it works well in chrome glContext, while can't be executed in 'webgl-raub'
gl.bufferData(target, buffer2 , usage) 
```
2. draw wireframe need extension 'OES_standard_derivatives'. what puzzles me is that I used this plugin directly, and it actually runs successfully. Which plugins are available for direct use?

**Comment by raub** [comment]
In 1, there are two things to notice:

- [arrayBuffer()](https://developer.mozilla.org/en-US/docs/Web/API/Body/arrayBuffer) returns a Promise. Are you sure Chrome correctly tolerates them, no `await` needed? Well we could make up for that.
- arrayBuffer()'s Promise is resolved with an `ArrayBuffer`, not `Float32Array`, and it is also possible to bypass that with an additional [bit of code](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer#Example).

Regarding the 2nd question, there is a lot of GL functions available, [here](https://github.com/node-3d/webgl-raub/blob/master/cpp/bindings.cpp) are all the exposed things. And more can be added according to [this](https://github.com/node-3d/deps-opengl-raub/blob/master/include/GL/glew.h) header.

**Comment by axmand** [comment]
Sorry, the code was written incorrectly. buffer2 should be like this.
``` javascript
fetch()
.then(response=>
  response.arrayBuffer())
.then(buffer2=>{
  //....
});
```
The current problem has been solved, I will try other extensions gradually. Thank you very much. 👍
