### ISSUE TITLE
Missing some API of WebGL

### ISSUE THREAD

**Issue by justgook** [node-3d/webgl-raub#7]
### Properties:
[`drawingBufferWidth`](https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/drawingBufferWidth)
[`drawingBufferHeight`](https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/drawingBufferHeight)

**Comment by justgook** [comment]
btw - ping me in discord `justgook#2839`

**Comment by raub** [comment]
Hi, this can probably be implemented with `glGetIntegerv(GL_VIEWPORT, viewport);`, but I'm not sure if the values will be correct for pixel ratio !=1 (Retina).

The other way around it is to implement it from the GLFW side. That will be correct for sure, but will also depend on the other module implementation.

**Comment by raub** [comment]
Fixed in webgl-raub@2.0.1
